Removes headshot stun + makes it harder to get eyeflash and confusion from headshots
Ofstation13/Nebula pull request #1
Opened 2023-07-21 18:26 UTC by Sparrowbird611

## Description of changes

## Why and what will this PR improve

## Authorship

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
bugfix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-07-31 22:05 UTC, Tennessee116 requested changes

2023-07-31 22:05 UTC, Tennessee116 commented on mods/content/bosnia/organs/internal/brain.dm
> +			addtimer(CALLBACK(src, .proc/brain_damage_callback, damage), rand(6, 20) SECONDS, TIMER_UNIQUE)
Literally just keep this and it should work. Remove everything else.

2023-09-05 00:02 UTC, Sparrowbird611 commented
Ok, this PR is functional.

2023-09-05 03:36 UTC, Tennessee116 commented
> Ok, this PR is functional.

Alright, I'll test it tomorrow and merge if no issues occur.

2023-09-05 20:26 UTC, merged